### ISSUE TITLE
Could not bundle single js ChimeSDK 3.7.0↑

### ISSUE THREAD

**Issue by hajime-goshima** [aws-samples/amazon-chime-sdk#243]
**Demo**

None. Command execution error.

**Describe the bug**

When a single file bundle is executed, the command execution fails due to dependency issues.

See below.

```bash
hazm@ubuntu:~/build_chime_sdk/aws_samples/utils/singlejs$ npm run bundle

> singlejs@0.1.0 bundle /home/hazm/build_chime_sdk/aws_samples/utils/singlejs
> rollup --config rollup.config.js

[!] Error: Cannot find module '@rollup/plugin-json'
Require stack:
- /home/hazm/build_chime_sdk/aws_samples/utils/singlejs/rollup.config.js
- /home/hazm/build_chime_sdk/aws_samples/utils/singlejs/node_modules/rollup/dist/shared/loadConfigFile.js
- /home/hazm/build_chime_sdk/aws_samples/utils/singlejs/node_modules/rollup/dist/bin/rollup
Error: Cannot find module '@rollup/plugin-json'
Require stack:
- /home/hazm/build_chime_sdk/aws_samples/utils/singlejs/rollup.config.js
- /home/hazm/build_chime_sdk/aws_samples/utils/singlejs/node_modules/rollup/dist/shared/loadConfigFile.js
- /home/hazm/build_chime_sdk/aws_samples/utils/singlejs/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/hazm/build_chime_sdk/aws_samples/utils/singlejs/rollup.config.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.require.extensions.<computed> [as .js] (/home/hazm/build_chime_sdk/aws_samples/utils/singlejs/node_modules/rollup/dist/shared/loadConfigFile.js:508:20)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

**To Reproduce**
1. Execute command `npm install`
2. Execute command `npm run bundle`

**Expected behavior**

Successful bundling of a single file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**

If the dependencies are modified as follows, the bundle will succeed.

```
  "devDependencies": {
    "@rollup/plugin-commonjs": "11.0.2",
    "@rollup/plugin-json": "^5.0.0",
    "@rollup/plugin-node-resolve": "^7.1.1",
    "rollup": "^2.3.2",
    "rollup-plugin-terser": "^7.0.0"
  },
```

**However, ChimeSDK Version 3.8.0 bundled with the same contents cannot be executed in a browser.**

3.8.0 ✗
3.7.0 ✗
3.6.0 ⭕
3.5.0 ⭕
3.0.0 ⭕

```
  "devDependencies": {
    "@rollup/plugin-commonjs": "11.0.2",
    "@rollup/plugin-json": "^5.0.0",
    "@rollup/plugin-node-resolve": "^7.1.1",
    "rollup": "^2.3.2",
    "rollup-plugin-terser": "^7.0.0"
  },
  "dependencies": {
    "amazon-chime-sdk-js": "^3.0.0"
  }
```

```
window.onload = async function () {
    alert(ChimeSDK.Versioning.sdkVersion)
}
```

```
Uncaught TypeError: Cannot read properties of undefined (reading 'promises')
    at amazon-chime-sdk.min.debug-19e6c61719b7ef20c01f60af184af668d8b21d1efddd16473ffa21d59a1097ea.js:3:504842
    at amazon-chime-sdk.min.debug-19e6c61719b7ef20c01f60af184af668d8b21d1efddd16473ffa21d59a1097ea.js:1:469
    at amazon-chime-sdk.min.debug-19e6c61719b7ef20c01f60af184af668d8b21d1efddd16473ffa21d59a1097ea.js:1:645
(anonymous) @ amazon-chime-sdk.min.debug-19e6c61719b7ef20c01f60af184af668d8b21d1efddd16473ffa21d59a1097ea.js:3
(anonymous) @ amazon-chime-sdk.min.debug-19e6c61719b7ef20c01f60af184af668d8b21d1efddd16473ffa21d59a1097ea.js:1
(anonymous) @ amazon-chime-sdk.min.debug-19e6c61719b7ef20c01f60af184af668d8b21d1efddd16473ffa21d59a1097ea.js:1
```
![image](https://user-images.githubusercontent.com/13103747/195032983-c21d01b2-8ba9-405f-b759-2be11001b905.png)

Is there a solution?

Thanks.

**Comment by eugenegodun** [comment]
I have to same issue

**Comment by xuesichao** [comment]
Hi we merged a fix for this issue, and I'm able to run `npm run bundle` in `singleJs` folder successfully. Could you please try again and give us feedback? Thank you.

**Comment by timanderson** [comment]
It runs but the global variable ChimeSDK is not defined

**Comment by timanderson** [comment]
Fixed by amending index.js to:

export * as default from 'amazon-chime-sdk-js';

**Comment by devalevenkatesh** [comment]
I have updated the export as suggested thanks for the tip @timanderson ! The fix is merged now.
